app:
  config:
    baseUrl: "https://api.openweathermap.org/data/2.5/weather"
    name: openweather
    apiKey:

spring:
  main:
    banner-mode: "off"

logging:
  level:
    root: INFO
  pattern:
    console:
